export const badges = [
  // --- Art Category ---
  {
    badgeId: 1,
    name: 'Hue Hunter',
    description: 'Fun, alliterative, color-centric explorer name.',
    image: '/badges/HueHunter.png',
    category: 'Art',
    tier: 'Common',
    colorTheme: 'Silver',
    finish: 'Matte silver base with subtle shine',
  },
  {
    badgeId: 2,
    name: 'Ink Rover',
    description: 'Ties to both drawing and wandering.',
    image: '/badges/InkRover.png',
    category: 'Art',
    tier: 'Uncommon',
    colorTheme: 'Gold',
    finish: 'Bright, polished golden rim and icon',
  },
  {
    badgeId: 3,
    name: 'Tone Tracer',
    description: 'Explorer vibe + art tone.',
    image: '/badges/ToneTracer.png',
    category: 'Art',
    tier: 'Rare',
    colorTheme: 'Sapphire Blue',
    finish: 'Deep, rich blue with cool metallic accents',
  },
  {
    badgeId: 4,
    name: 'Canvas Drifter',
    description: 'Poetic, paints you as an artistic wanderer.',
    image: '/badges/CanvasDrifter.png',
    category: 'Art',
    tier: 'Epic',
    colorTheme: 'Royal Purple',
    finish: 'Elegant purple with slight gradient + glow',
  },
  {
    badgeId: 5,
    name: 'Museborne',
    description: 'Strong final title, mythical-feeling, fits Zephyra.',
    image: '/badges/Museborne.png',
    category: 'Art',
    tier: 'Legendary',
    colorTheme: 'Red & Gold Gradient',
    finish: 'Heroic blend — fiery red into glowing gold',
  },

  // --- Food Category ---
  {
    badgeId: 6,
    name: 'Nibble Nomad',
    description: 'Alliteration, feels light and journey-based.',
    image: '/badges/NibbleNomad.png',
    category: 'Food',
    tier: 'Common',
    colorTheme: 'Silver',
    finish: 'Matte silver base with subtle shine',
  },
  {
    badgeId: 7,
    name: 'Bite Seeker',
    description: 'Short, adventurous, and thematic.',
    image: '/badges/BiteSeeker.png',
    category: 'Food',
    tier: 'Uncommon',
    colorTheme: 'Gold',
    finish: 'Bright, polished golden rim and icon',
  },
  {
    badgeId: 8,
    name: 'Taste Raider',
    description: 'Strong, feels earned.',
    image: '/badges/TasteRaider.png',
    category: 'Food',
    tier: 'Rare',
    colorTheme: 'Sapphire Blue',
    finish: 'Deep, rich blue with cool metallic accents',
  },
  {
    badgeId: 9,
    name: 'Spice Whisperer',
    description: 'Elegant and culture-rooted.',
    image: '/badges/SpiceWhisperer.png',
    category: 'Food',
    tier: 'Epic',
    colorTheme: 'Royal Purple',
    finish: 'Elegant purple with slight gradient + glow',
  },
  {
    badgeId: 10,
    name: 'Forkborne',
    description: 'Unique, mythical-sounding (like “Stormborn” or “Zephyrborn”).',
    image: '/badges/Forkborne.png',
    category: 'Food',
    tier: 'Legendary',
    colorTheme: 'Red & Gold Gradient',
    finish: 'Heroic blend — fiery red into glowing gold',
  },

  // --- History Category ---
  {
    badgeId: 11,
    name: 'Trail Walker',
    description: 'Suggests beginnings, footsteps, paths.',
    image: '/badges/TrailWalker.png',
    category: 'History',
    tier: 'Common',
    colorTheme: 'Silver',
    finish: 'Matte silver base with subtle shine',
  },
  {
    badgeId: 12,
    name: 'Echo Finder',
    description: 'Poetic + mysterious — perfect for historic ruins or artifacts.',
    image: '/badges/EchoFinder.png',
    category: 'History',
    tier: 'Uncommon',
    colorTheme: 'Gold',
    finish: 'Bright, polished golden rim and icon',
  },
  {
    badgeId: 13,
    name: 'Relic Seeker',
    description: 'Classic adventurer badge — feels rare.',
    image: '/badges/RelicSeeker.png',
    category: 'History',
    tier: 'Rare',
    colorTheme: 'Sapphire Blue',
    finish: 'Deep, rich blue with cool metallic accents',
  },
  {
    badgeId: 14,
    name: 'Chrono Drifter',
    description: 'Mythical and exploratory, time-travel vibes.',
    image: '/badges/ChronoDrifter.png',
    category: 'History',
    tier: 'Epic',
    colorTheme: 'Royal Purple',
    finish: 'Elegant purple with slight gradient + glow',
  },
  {
    badgeId: 15,
    name: 'Timeborne',
    description: 'Elegant and powerful, in the same style as "Museborne" and "Forkborne".',
    image: '/badges/Timeborne.png',
    category: 'History',
    tier: 'Legendary',
    colorTheme: 'Red & Gold Gradient',
    finish: 'Heroic blend — fiery red into glowing gold',
  },

  // --- Culture Category ---
  {
    badgeId: 16,
    name: 'Ritual Rover',
    description: 'Alliteration + explorer tone for cultural beginnings.',
    image: '/badges/RitualRover.png',
    category: 'Culture',
    tier: 'Common',
    colorTheme: 'Silver',
    finish: 'Matte silver base with subtle shine',
  },
  {
    badgeId: 17,
    name: 'Tradewind Scout',
    description: 'Evokes travel, exchange, and ancient routes.',
    image: '/badges/TradewindScout.png',
    category: 'Culture',
    tier: 'Uncommon',
    colorTheme: 'Gold',
    finish: 'Bright, polished golden rim and icon',
  },
  {
    badgeId: 18,
    name: 'Symbol Seeker',
    description: 'Deep, mysterious; about uncovering meaning.',
    image: '/badges/SymbolSeeker.png',
    category: 'Culture',
    tier: 'Rare',
    colorTheme: 'Sapphire Blue',
    finish: 'Deep, rich blue with cool metallic accents',
  },
  {
    badgeId: 19,
    name: 'Myth Walker',
    description: 'Poetic, linked to stories and folklore.',
    image: '/badges/MythWalker.png',
    category: 'Culture',
    tier: 'Epic',
    colorTheme: 'Royal Purple',
    finish: 'Elegant purple with slight gradient + glow',
  },
  {
    badgeId: 20,
    name: 'Zephyrite',
    description: 'Unique to your world — legendary status and brand-connected.',
    image: '/badges/Zephyrite.png',
    category: 'Culture',
    tier: 'Legendary',
    colorTheme: 'Red & Gold Gradient',
    finish: 'Heroic blend — fiery red into glowing gold',
  },

  // --- Adventure Category ---
  {
    badgeId: 21,
    name: 'Trail Treader',
    description: 'Grounded start, ties to hikes, forests, and new paths.',
    image: '/badges/TrailTreader.png',
    category: 'Adventure',
    tier: 'Common',
    colorTheme: 'Silver',
    finish: 'Matte silver base with subtle shine',
  },
  {
    badgeId: 22,
    name: 'Cliff Caller',
    description: 'Evokes thrill, nature, and danger with poetic flair.',
    image: '/badges/CliffCaller.png',
    category: 'Adventure',
    tier: 'Uncommon',
    colorTheme: 'Gold',
    finish: 'Bright, polished golden rim and icon',
  },
  {
    badgeId: 23,
    name: 'Edgewalker',
    description: 'Feels daring — rare and boundary-pushing.',
    image: '/badges/Edgewalker.png',
    category: 'Adventure',
    tier: 'Rare',
    colorTheme: 'Sapphire Blue',
    finish: 'Deep, rich blue with cool metallic accents',
  },
  {
    badgeId: 24,
    name: 'Stormrider',
    description: 'Elemental, intense, and powerful.',
    image: '/badges/Stormrider.png',
    category: 'Adventure',
    tier: 'Epic',
    colorTheme: 'Royal Purple',
    finish: 'Elegant purple with slight gradient + glow',
  },
  {
    badgeId: 25,
    name: 'Zephyrbound',
    description: 'Thematically tied to Zephyra’s name; poetic and mythical.',
    image: '/badges/Zephyrbound.png',
    category: 'Adventure',
    tier: 'Legendary',
    colorTheme: 'Red & Gold Gradient',
    finish: 'Heroic blend — fiery red into glowing gold',
  },

  // --- Hidden Gems Category ---
  {
    badgeId: 26,
    name: 'Pathfinder',
    description: 'The classic explorer starting point.',
    image: '/badges/Pathfinder.png',
    category: 'Hidden Gems',
    tier: 'Common',
    colorTheme: 'Silver',
    finish: 'Matte silver base with subtle shine',
  },
  {
    badgeId: 27,
    name: 'Vault Seeker',
    description: 'Adds secrecy and treasure-hunting flavor.',
    image: '/badges/VaultSeeker.png',
    category: 'Hidden Gems',
    tier: 'Uncommon',
    colorTheme: 'Gold',
    finish: 'Bright, polished golden rim and icon',
  },
  {
    badgeId: 28,
    name: 'Hollow Runner',
    description: 'Feels like navigating lost tunnels and alleys.',
    image: '/badges/HollowRunner.png',
    category: 'Hidden Gems',
    tier: 'Rare',
    colorTheme: 'Sapphire Blue',
    finish: 'Deep, rich blue with cool metallic accents',
  },
  {
    badgeId: 29,
    name: 'Shadow Knower',
    description: 'Mystical, implies deep awareness.',
    image: '/badges/ShadowKnower.png',
    category: 'Hidden Gems',
    tier: 'Epic',
    colorTheme: 'Royal Purple',
    finish: 'Elegant purple with slight gradient + glow',
  },
  {
    badgeId: 30,
    name: 'Gemwoken',
    description: 'Like “awoken by the gems” — unique, powerful, branded.',
    image: '/badges/Gemwoken.png',
    category: 'Hidden Gems',
    tier: 'Legendary',
    colorTheme: 'Red & Gold Gradient',
    finish: 'Heroic blend — fiery red into glowing gold',
  },
];
